### ISSUE TITLE
Android room database - LiveData paging slow appear when a lot of insert/update into database

### ISSUE THREAD

**Issue by tvhieuit** [android/architecture-components-samples#265] opened 2017-12-27 03:30 UTC
I'm working in a project realtime with LiveData and Paging database
I meet the issue:
 -- My list take long time to appear when have a lot of insert/update to database.

`val viewModel = ViewModelProviders.of(this).get(MyViewModel::class.java)
		viewModel.init(database)
		viewModel.getUserList()?.observe(this, Observer {
			println("load paging ::::   ${it?.size}")
		})`

could anybody help me

Thank you so much.
Hieu Tran

**Comment by a1018875550** [comment] 2018-02-08 03:55
why you close this? have any solution？

**Comment by tvhieuit** [comment] 2018-02-08 06:24
currently, I don't have any solution :)

**Comment by a1018875550** [comment] 2018-02-08 08:24
I use LiveData to my project without room, 
I find when I change database the ui update very slow.
It's there a good way to solve this? to update sql or about ui code? Thanks

**Comment by tvhieuit** [comment] 2018-02-08 08:40
maybe, you load large database to UI?
I also meet this issue when I got database realtime (same as chat realtime)

**Comment by nooballday** [comment] 2018-03-16 06:34
I can confirm it, i tried using Room with Livedata and the changes is quite slow.

**Comment by tvhieuit** [comment] 2018-03-16 08:22
Do you have any solution for this?

**Comment by tvhieuit** [comment] 2018-09-12 07:48
@NhatPham94 I know, but how to fix it :D

**Comment by NhatPham94** [comment] 2018-09-12 07:55
@tvhieuit Currently I'm working on a demo with Paging lib + Room + LiveData, I trigger updates and try to debug and see what's going on. The result is Room only loads specific size that I config with Paging lib (page size) instead of re-create the whole query when using it without Paging lib.

**Comment by NhatPham94** [comment] 2018-10-16 07:47
@tvhieuit Have you found any solutions ?

**Comment by ChrisCraik** [comment] 2018-10-16 17:11
Currently, the Paging library will start loading from the DB, and if content in the DB has changed by the time it's done, we won't send the result, and will instead reload.

The behavior is intended to avoid sending too many, too-similar lists to the UI, but we could make it smarter to avoid the problem (send something to avoid spinning continuously). If you file a bug ( https://issuetracker.google.com/issues/new?component=413106&template=1096385 ), I can look into it, especially if you have a sample repro project.

**Comment by saravanakumarthamilselvi** [comment] 2019-05-04 14:19
Hi , Anybody found resolutions for this issue.

**Comment by M66B** [comment] 2019-07-22 09:54
Related issue with a possible solution: https://issuetracker.google.com/issues/134685570

**Comment by sidthakkar12** [comment] 2019-10-23 13:32
Hope you have fired query in doAsync{} !!

**Comment by M66B** [comment] 2019-10-23 13:36
@sidthakkar12 paging is by definition async, so maybe you don't understand this issue.

**Comment by jemmycalak** [comment] 2019-11-26 16:43
I use this https://realm.io/blog/realm-java-0-84-0/
 to insert many data, I was try insert data up to 2M and no take long time.

but it take so many size of stored to save that data.

**Comment by jemmycalak** [comment] 2019-11-27 16:25
I try this code on room and get better time to insert many data

@Dao
interface Dao{
   @Insert(onConflict = REPLACE)
   fun insertData(m :List<YourModel>)
}

**Comment by nikolamin** [comment] 2020-04-01 14:34
I experienced the same issue and i found that i have two updates, one after another, on the same table. The first update was triggering the observer but the changes were not relevant for the query and no results were returned, the second update wasn't triggering the observer immediately because it was busy querying the data after changes from the first update and the event has been postponed. Merging to updates into one query has fixed the issue (if it is not possible you may try using [@Transcation](https://developer.android.com/reference/android/arch/persistence/room/Transaction) )

**Comment by dlam** [comment] 2021-02-10 00:03
As Chris mentioned - this seems to be working as intended.

In v3 APIs, we have an open-issue to better support the high frequency updates use-case by allowing a stream-based API for delivering item / page updates without invalidation loop: https://issuetracker.google.com/149482600

Please follow / comment / +1 there!

**Closed by dlam** 2021-02-10 00:03 UTC
Labels: paging
