### ISSUE TITLE
GithubBrowserSample: AppInjector and HasSupportFragmentInjector

### ISSUE THREAD

**Issue by leinardi** [android/architecture-components-samples#242] opened 2017-11-29 11:57 UTC
Why is the `handleActivity()` method checking if activity is instanceof `HasSupportFragmentInjector`?
Shouldn't an injectable Activity just implements `Injectable`, like the interface javadoc suggest, instead of `HasSupportFragmentInjector`?

https://github.com/googlesamples/android-architecture-components/blob/1532c562bb4d25f8469471478195160fd96b5db7/GithubBrowserSample/app/src/main/java/com/android/example/github/di/AppInjector.java#L80

https://github.com/googlesamples/android-architecture-components/blob/1532c562bb4d25f8469471478195160fd96b5db7/GithubBrowserSample/app/src/main/java/com/android/example/github/di/Injectable.java#L20

**Comment by pzmudzinski** [comment] 2017-12-04 15:03
Also it's unclear how fragments specified directly in XML should be configured.

**Comment by iammert** [comment] 2017-12-21 16:43
You need to implement HasSupportFragmentInjector in your Activity If you want to use injection in your fragments. I think this is why it is checking it in the line 80.  But this brings another question to my mind. What if the developer doesn't implement HasSupportFragment injector? AppInjector still tries to inject fragments too. And eventually app will crash.

**Comment by ianhanniballake** [comment] 2020-01-27 05:17
Duplicate of #203

**Closed by ianhanniballake** 2020-01-27 05:17 UTC
