### ISSUE TITLE
Lifecycle owner when using Data-Binding & LiveData

### ISSUE THREAD

**Issue by AlexisQapa** [android/architecture-components-samples#310] opened 2018-02-15 15:42 UTC
Hi, 

I'm evaluating data binding with live data (+kotlin) . So far so great !
Everything works great but I'm wondering why when I use an include the lifecycleowner is not transmitted to the include.

I bind my layout like this :
val binding = DataBindingUtil.setContentView<SomeBinding>(this, getLayoutId())
binding.let {
            it.viewModel = viewModel
            it.setLifecycleOwner(this) (1)
            //it.SomeInclude?.setLifecycleOwner(this) (2)
}

If I put all my layout in the main layout and keep only (1) it works,

Then If put a part of my layout into SomeLayout, I loose the observer

If I uncomment (2), it works, so I'm sure the lifecycle owner is not properly transmitted when using include.

Is this the expected behaviour or is this a bug ? Is there a way to avoid (2) because it's easily missable.

**Comment by pedromvu** [comment] 2018-09-11 22:26
@AlexisQapa I am experiencing something similar, although in my case it does not get fixed by calling setLifecycleOwner to the included component, I checked the code and the first setLifecycleOwner does call that same method on all the included layout components, so both ways it should be doing the same.

In my case the problem is only happening randomly after an interruption (pause, then resume on the view)

Sometimes after that, the binding view stops being synced with the bound fields.

The funny thing is that I am not actually using LiveData, just simple bindings and RxJava 2 to send info from ViewModel to Fragment, and if I remove the setLifecycleOwner call everything seems to work correctly.

**Comment by kbrz** [comment] 2018-09-21 09:07
@pedromvu Hi. I am facing exactly the same issue. Have you found any workaround yet?

**Comment by kbrz** [comment] 2018-09-21 16:13
Actually I can see that generated binding class is overriding `setLifecycleOwner` to pass `lifecycleOwner` to the includes.

My problem is that when I set binding's `lifecycleOwner` my binding (other than `LiveData`) stop working. Upon entering activity (A) everything works fine. But when I open another activity (B) and then go back to the previous one (A) binding does not work. I set some breakpoint trying to debug it and I can see that `mPendingBinding` (I do now have a code in front of me right now so this flag's name can be slightly different) is `true`, but binding is never executed.

**Comment by pedromvu** [comment] 2018-09-21 18:12
@kbrz I found exactly the same, although in my phone it only happened randomly, must be a bug with the library.

**Comment by shaazps** [comment] 2018-10-18 17:45
Did anyone find a workaround for this issue?
I had to remove  binding.setLifecycleOwner(...) and then also make the ObservableField<> in my view model to final.  Is there a better way?

**Comment by FelipeRRM** [comment] 2018-11-12 13:44
I am not actually using a include, but I have a recyclerview in which every item inside it is data-bound, so when creating the view holders from the layout files, I also set the lifecycleOwner to the binding of each item (I have to pass the lifecycleOwner to the adapter). When I do this, LiveData in each individual list item triggers a UI update as intended, but it makes the Fragment's LiveData stop updating other Fragment's UI. Really tricky thing.

**Comment by erickentry** [comment] 2018-12-31 03:49
I don't know if this would help, but what we did in our project is registering lifecycle owner `onStart` and unregister it `onStop`. It works on Activities and Fragments, including any `include` within the layouts.

```
override fun onStart() {
    super.onStart()
    binding.setLifecycleOwner(this)
}

override fun onStop() {
    binding.setLifecycleOwner(null)
    super.onStop()
}
```

While for the `include` itself, we need to pass variable from _MainLayout_ to _SomeLayout_.

```
<!-- MainLayout -->
<layout ...>
  <data>
    <variable name="someModel" type="SomeViewModel"/>
  </data>

  <Linear Layout ...>
    <include 
      layout="@layout/SomeLayout"
      ...
      app:someModel="@{ someModel }" />
  </LinearLayout>
</layout>

<!-- SomeLayout -->
<layout ...>
  <data>
    <variable name="someModel" type="SomeViewModel"/>
  </data>

  <Linear Layout ...>
    <TextView
      ...
      android:text="@{ someModel.someLiveData }" />
  </LinearLayout>
</layout>
```

**Comment by zivids** [comment] 2019-04-18 03:46
> Did anyone find a workaround for this issue?
> I had to remove binding.setLifecycleOwner(...) and then also make the ObservableField<> in my view model to final. Is there a better way?

I solved it by update the com.android.tools.build:gradle and gradle-wrapper to the latest version

**Comment by roxfives** [comment] 2019-11-28 16:30
> Hi,
> 
> I'm evaluating data binding with live data (+kotlin) . So far so great !
> Everything works great but I'm wondering why when I use an include the lifecycleowner is not transmitted to the include.
> 
> I bind my layout like this :
> val binding = DataBindingUtil.setContentView(this, getLayoutId())
> binding.let {
> it.viewModel = viewModel
> it.setLifecycleOwner(this) (1)
> //it.SomeInclude?.setLifecycleOwner(this) (2)
> }
> 
> If I put all my layout in the main layout and keep only (1) it works,
> 
> Then If put a part of my layout into SomeLayout, I loose the observer
> 
> If I uncomment (2), it works, so I'm sure the lifecycle owner is not properly transmitted when using include.
> 
> Is this the expected behaviour or is this a bug ? Is there a way to avoid (2) because it's easily missable.

I had this issue because I was using the wrong namespace in the include tag. I was using `app` instead of `bind` (the correct one for data-binding).

I hope it helps you :) 

Ex.:
```
<include
    layout="@layout/my_layout"
    bind:myData="@{viewModel.myData}"/>
```

**Comment by ianhanniballake** [comment] 2020-01-27 00:28
This doesn't seem to be an issue with the samples. You can file an issue against DataBinding on [the issue tracker](https://issuetracker.google.com/issues/new?component=192721) if you're still having an issue.

**Closed by ianhanniballake** 2020-01-27 00:28 UTC
